[meta]
fingerprint = "0x3296925C79114CF3"

[[packets]]
id = 33
struct_name = "RatFocHeartbeat"
packed = false
byte_size = 24

[[packets.fields]]
name = "tick_ms"
c_type = "uint32_t"
offset = 0
size = 4

[[packets.fields]]
name = "electrical_angle"
c_type = "float"
offset = 4
size = 4

[[packets.fields]]
name = "iq_target"
c_type = "float"
offset = 8
size = 4

[[packets.fields]]
name = "duty_u"
c_type = "float"
offset = 12
size = 4

[[packets.fields]]
name = "duty_v"
c_type = "float"
offset = 16
size = 4

[[packets.fields]]
name = "duty_w"
c_type = "float"
offset = 20
size = 4
